# ==============================
# = APPLICATION
# ==============================
spring.application.name=product-service
server.port=8120

# ==============================
# = GRPC
# ==============================
grpc.server.port=8122

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/atlas
spring.datasource.username=umut
spring.datasource.password=umut

# ===============================
# = AWS
# ===============================
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=umut
spring.cloud.aws.credentials.secret-key=umut

# ===============================
# = AWS - S3
# ===============================
spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=true
aws.s3.bucket.name=atlas-images
