# ==============================
# = APPLICATION
# ==============================
spring.application.name=notification-service
server.port=8110

# ==============================
# = MAIL
# ==============================
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=noreply@atlas.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ==============================
# = MESSAGING QUEUE - RABBITMQ
# ==============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=umut
spring.rabbitmq.password=umut

# ==============================
# = VALUES - RABBITMQ EXCHANGES, QUEUES
# ==============================
atlas.rabbitmq.queue.email=email_notification_queue
atlas.rabbitmq.exchange.user=user_events_exchange
atlas.rabbitmq.routing-key.user-registered=user.registered.route