version: "3.8"

services:
  postgres:
    container_name: atl_postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: umut
      POSTGRES_PASSWORD: umut
    volumes:
      - atl_postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U umut -d atlas" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - atl_network

  maildev:
    container_name: atl_maildev
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  atl_network:
    driver: bridge

volumes:
  atl_postgres-data: { }